using System.IO;
using FellowOakDicom;

namespace DicomTools.Tests;

public class DicomFileOperationsTests
{
    [Fact]
    public void DicomFile_Create_WithDataset()
    {
        var dataset = new DicomDataset
        {
            { DicomTag.PatientName, "Test^Patient" },
            { DicomTag.PatientID, "TEST-001" },
            { DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage },
            { DicomTag.SOPInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID() }
        };

        var file = new DicomFile(dataset);

        Assert.NotNull(file.Dataset);
        Assert.NotNull(file.FileMetaInfo);
        Assert.Equal("Test^Patient", file.Dataset.GetSingleValue<string>(DicomTag.PatientName));
    }

    [Fact]
    public void DicomFile_FileMetaInfo_AutoGenerated()
    {
        var dataset = new DicomDataset(DicomTransferSyntax.ExplicitVRLittleEndian)
        {
            { DicomTag.PatientName, "Meta^Test" },
            { DicomTag.PatientID, "META-001" },
            { DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage },
            { DicomTag.SOPInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID() }
        };

        var file = new DicomFile(dataset);

        Assert.NotNull(file.FileMetaInfo.MediaStorageSOPClassUID);
        Assert.NotNull(file.FileMetaInfo.MediaStorageSOPInstanceUID);
        Assert.NotNull(file.FileMetaInfo.TransferSyntax);
        Assert.NotNull(file.FileMetaInfo.ImplementationClassUID);
    }

    [Fact]
    public void DicomFile_SaveToStream_Success()
    {
        var dataset = CreateMinimalDataset();
        var file = new DicomFile(dataset);

        using var memory = new MemoryStream();
        file.Save(memory);

        Assert.True(memory.Length > 0);
        Assert.True(memory.Length > 132);
    }

    [Fact]
    public void DicomFile_SaveToFile_Success()
    {
        var tempPath = Path.Combine(Path.GetTempPath(), $"dicom-test-{Guid.NewGuid():N}.dcm");

        try
        {
            var dataset = CreateMinimalDataset();
            var file = new DicomFile(dataset);
            file.Save(tempPath);

            Assert.True(File.Exists(tempPath));

            var reloaded = DicomFile.Open(tempPath);
            Assert.Equal(
                dataset.GetSingleValue<string>(DicomTag.SOPInstanceUID),
                reloaded.Dataset.GetSingleValue<string>(DicomTag.SOPInstanceUID));
        }
        finally
        {
            if (File.Exists(tempPath))
                File.Delete(tempPath);
        }
    }

    [Fact]
    public async Task DicomFile_OpenAsync_Success()
    {
        var path = SampleSeriesHelper.GetFirstFilePath();

        var file = await DicomFile.OpenAsync(path);

        Assert.NotNull(file);
        Assert.NotNull(file.Dataset);
        Assert.True(file.Dataset.Contains(DicomTag.SOPInstanceUID));
    }

    [Fact]
    public async Task DicomFile_SaveAsync_Success()
    {
        var tempPath = Path.Combine(Path.GetTempPath(), $"dicom-async-{Guid.NewGuid():N}.dcm");

        try
        {
            var dataset = CreateMinimalDataset();
            var file = new DicomFile(dataset);
            await file.SaveAsync(tempPath);

            Assert.True(File.Exists(tempPath));

            var reloaded = await DicomFile.OpenAsync(tempPath);
            Assert.NotNull(reloaded.Dataset);
        }
        finally
        {
            if (File.Exists(tempPath))
                File.Delete(tempPath);
        }
    }

    [Fact]
    public void DicomFile_OpenFromStream_Success()
    {
        var dataset = CreateMinimalDataset();
        var file = new DicomFile(dataset);

        using var memory = new MemoryStream();
        file.Save(memory);
        memory.Position = 0;

        var reloaded = DicomFile.Open(memory);

        Assert.NotNull(reloaded);
        Assert.Equal(
            dataset.GetSingleValue<string>(DicomTag.PatientID),
            reloaded.Dataset.GetSingleValue<string>(DicomTag.PatientID));
    }

    [Fact]
    public void DicomFile_HasValidPreamble()
    {
        var dataset = CreateMinimalDataset();
        var file = new DicomFile(dataset);

        using var memory = new MemoryStream();
        file.Save(memory);
        memory.Position = 0;

        var preamble = new byte[128];
        memory.Read(preamble, 0, 128);

        var prefix = new byte[4];
        memory.Read(prefix, 0, 4);

        Assert.Equal("DICM", System.Text.Encoding.ASCII.GetString(prefix));
    }

    [Fact]
    public void DicomFile_Clone_CreatesIndependentCopy()
    {
        var original = new DicomFile(CreateMinimalDataset());
        var cloned = original.Clone();

        cloned.Dataset.AddOrUpdate(DicomTag.PatientName, "Cloned^Patient");

        Assert.NotEqual(
            original.Dataset.GetSingleValue<string>(DicomTag.PatientName),
            cloned.Dataset.GetSingleValue<string>(DicomTag.PatientName));
    }

    [Fact]
    public void DicomFile_TransferSyntax_CanBeAccessed()
    {
        var dataset = new DicomDataset(DicomTransferSyntax.ExplicitVRLittleEndian);
        dataset.Add(DicomTag.PatientName, "Transfer^Test");
        dataset.Add(DicomTag.PatientID, "TX-001");
        dataset.Add(DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage);
        dataset.Add(DicomTag.SOPInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID());

        var file = new DicomFile(dataset);

        Assert.NotNull(file.FileMetaInfo.TransferSyntax);
    }

    [Fact]
    public void DicomFile_ImplementationVersion_CanBeSet()
    {
        var dataset = CreateMinimalDataset();
        var file = new DicomFile(dataset);

        file.FileMetaInfo.ImplementationVersionName = "FODICOM_TEST";

        using var memory = new MemoryStream();
        file.Save(memory);
        memory.Position = 0;

        var reloaded = DicomFile.Open(memory);
        Assert.Equal("FODICOM_TEST", reloaded.FileMetaInfo.ImplementationVersionName);
    }

    private static DicomDataset CreateMinimalDataset()
    {
        return new DicomDataset(DicomTransferSyntax.ExplicitVRLittleEndian)
        {
            { DicomTag.PatientName, "Minimal^Patient" },
            { DicomTag.PatientID, "MIN-001" },
            { DicomTag.StudyInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID() },
            { DicomTag.SeriesInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID() },
            { DicomTag.SOPInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID() },
            { DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage }
        };
    }
}
